substitutions:
  device_name: humidity_sensor
esphome:
  name: $device_name
  platform: ESP8266
  board: d1_mini_lite
  on_boot:
    - priority: -300
      then:
        - script.execute: set_online
  on_loop:
    if:
      condition:
        mqtt.connected:
      then:
        - script.execute: low_voltage_cut_off

logger:
  level: DEBUG

wifi:
  fast_connect: true
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.26
    gateway: 192.168.1.1
    subnet: 255.255.255.0

captive_portal:

sensor:
  - platform: dht
    model: DHT22
    pin: D2
    temperature:
      name: "Room Temperature"
    humidity:
      name: "Room Humidity"
    update_interval: 5s
  - platform: adc
    name: ${device_name}.battery_voltage
    pin: A0
    id: "VCC"
    update_interval: 0.5s
    filters:
      - median:
          window_size: 10
          send_every: 10
      - multiply: 6.6
      - offset: 0.1
  - platform: template
    name: ${device_name}.battery_level
    unit_of_measurement: '%'
    update_interval: 5s
    # 3.5V to 4.1V
    lambda: |-
      return ((id(VCC).state - 3.5) / 0.6) * 100.00;
      

# Enable Home Assistant API
api:

ota:
  password: !secret hass_api_password

deep_sleep:
   id: deep_sleep_1
   run_duration: 20s
   sleep_duration: 30min

mqtt:
  broker: !secret mqtt_url
  username: !secret mqtt_user
  password: !secret mqtt_password
  birth_message:
  will_message:
  on_message:
    - topic: ${device_name}/sleep_mode
      payload: 'OFF'
      then:
        - deep_sleep.prevent: deep_sleep_1
    - topic: ${device_name}/sleep_mode
      payload: 'GO_TO_SLEEP'
      then:
        - deep_sleep.enter: deep_sleep_1

script:
  - id: set_online
    then:
    - mqtt.publish:
        topic: ${device_name}/status
        payload: "online"
        retain: true
  - id: low_voltage_cut_off
    then:
    - if:
        condition:
          lambda: 'return (id(VCC).state < 3.5);'
        then:
          - mqtt.publish:
              topic: ${device_name}/status
              payload: 'offline - low battery'
              retain: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
          - deep_sleep.enter:
              id: deep_sleep_1
              sleep_duration: 0s
